language: java
dist: trusty

addons:
  sonarcloud:
    organization: "jafl-github"
    
    env:
    -MAVEN_VERSION=3.3.8
install:
-"mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
script:
  - "mvn cobertura:cobertura"
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)
