language: java 

jdk:

-openjdk8

env:
 - MAVEN_VERSION=3.2.5

install:
- "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"

script:
./mvnw clean install

notification:
email: 1830912@students.wits.ac.za 




