language: java 

jdk:

-openjdk8

 
 before_install: 
 - chmod +x mvnw 

install:
./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#- "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"

script:
./mvnw test -B

notification:
email: 1830912@students.wits.ac.za 




